name: edgex-ui
base: core18 
version: '2.0' 
# version-script: |
#   echo $(cat VERSION)-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
summary: EdgeX Web management UI
description: |
  .
grade: stable
confinement: strict

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64
  # - build-on: i386

apps:
  edgex-ui:
    command: bin/edgex-ui-wrapper.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind

parts:
  web-static:
    plugin: dump
    source: cmd/edgex-ui-server
    prime: 
       - static/web/*
  local-snap-assets:
    plugin: dump
    source: snap/local/runtime-helpers
    prime:
      - bin/*

  edgex-ui:
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, zip, pkg-config]
    build-snaps:
      - go/1.16/stable
    stage-packages: [libzmq5]
    override-build: |
      go mod tidy
      make build
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/config/edgex-ui-server/res"
      cp cmd/edgex-ui-server/edgex-ui-server $SNAPCRAFT_PART_INSTALL/bin/edgex-ui-server
      # change the StaticResourcesPath to point to $SNAP
      cat "./cmd/edgex-ui-server/res/configuration.toml" | \
        sed -e s@"StaticResourcesPath = \"./static\""@"StaticResourcesPath = \"\$SNAP/static\""@ > \
       "$SNAPCRAFT_PART_INSTALL/config/edgex-ui-server/res/configuration.toml"

